version: '3'

services:

  cert:
    image: pgarrett/openssl-alpine
    container_name: cert
    volumes:
      - ./certs:/etc/ssl/certs

  ldap:
    build:
      context: .
    container_name: ldap
    ports:
      - 636:636
    environment:
      - CA_FILE=/etc/ssl/certs/ca.pem
      - KEY_FILE=/etc/ssl/certs/public.key
      - CERT_FILE=/etc/ssl/certs/public.crt
    volumes:
      - ./certs:/etc/ssl/certs
      - ./users.ldif:/ldif/users.ldif
